import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import { WebVitals } from "@/components/WebVitals"
import I18nProviderWrapper from "@/components/I18nProviderWrapper"; // 导入包装器

// 移除以下两行导入
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
// import { AppSidebar } from "@/components/AppSidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  params, // Next.js 13+ App Router 会传递 params，其中包含 locale
}: Readonly<{
  children: React.ReactNode
  params: { locale: string } // 添加 locale 到 params 类型
}>) {
  // 如果 i18n 实例需要根据 locale 动态改变语言，可以在这里处理
  // useEffect(() => {
  //   if (params.locale && i18n.language !== params.locale) {
  //     i18n.changeLanguage(params.locale);
  //   }
  // }, [params.locale]);
  // 注意：上面的 useEffect 逻辑更适合放在 I18nProviderWrapper 内部，因为它是一个客户端组件
  // 服务端获取 i18n 实例
  return (
    <html lang={params.locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <I18nProviderWrapper locale={params.locale}>
          {children}
        </I18nProviderWrapper>
        <WebVitals />
        <Toaster />
      </body>
    </html>
  )
}
